# Generated by Django 2.2.7 on 2019-11-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'myinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('star', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'schedule',
                'managed': False,
            },
        ),
    ]
